# Response by message
messageEnable: false
message: "Please don't use inappropriate word"

# Response by command
commandEnable: false
command: "warn %player% inappropriate word"

# World list
words:
  - word
  - word
  - word
  - word
